import fs from 'node:fs';
import path from 'node:path';
import {viewerPanel as renderViewerPanel} from './viewer-panel.mjs';
import {designPreviews} from './design-previews.mjs';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const site=read('content/site.json'),research=read('content/research.json'),team=read('content/team.json'),resources=read('content/resources.json'),news=read('content/news.json');
const base=(process.env.BASE_PATH||'').replace(/\/$/,'');
if(base&&(!base.startsWith('/')||base.includes('..')||/[?#]/.test(base)))throw new Error('Invalid BASE_PATH');
const origin=(process.env.SITE_URL||'http://127.0.0.1:4321').replace(/\/$/,'');
const emailDisplay=site.email;
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json=x=>JSON.stringify(x).replace(/</g,'\\u003c');
const url=p=>/^(https?:|mailto:|tel:|#)/.test(p)?p:base+p;
const absolute=p=>/^https?:/.test(p)?p:origin+url(p);
const link=(href,label,cls='',attrs='')=>`<a class="${cls}" href="${e(url(href))}" ${attrs}>${label}</a>`;
const image=(src,alt,cls='',eager=false)=>`<img class="${cls}" src="${e(url(src))}" alt="${e(alt)}" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;
const paperUrl=p=>'/publications/'+p.slug+'/';
const papers=fs.readdirSync('content/publications').filter(f=>f.endsWith('.json')).map(f=>{
 const p=read('content/publications/'+f);
 for(const k of ['slug','title','year','authors','journal','summary','topics'])if(!p[k])throw new Error(`${f}: missing ${k}`);
 if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(p.slug)||!Number.isInteger(p.year)||!Array.isArray(p.topics))throw new Error(`${f}: invalid metadata`);
 for(const k of ['pdf','publisher','doi','code','dataset'])if(p[k]&&!/^(https:\/\/|\/(?!\/))/.test(p[k]))throw new Error(`${f}: invalid ${k}`);
 if(p.image&&!p.imageAlt)throw new Error(`${f}: missing image description`);
 p.type||='Article';p.publicationStatus||=p.type==='Preprint'?'Preprint':'Published';return p;
}).sort((a,b)=>b.year-a.year||(b.datePublished||'').localeCompare(a.datePublished||'')||(a.order??99)-(b.order??99)||a.title.localeCompare(b.title));
if(new Set(papers.map(p=>p.slug)).size!==papers.length)throw new Error('Duplicate publication slug');
const preprints=papers.filter(p=>p.type==='Preprint'),published=papers.filter(p=>p.type!=='Preprint');
const nature=papers.find(p=>String(p.doi).includes('s41586-026-10454-2'));
const topics=[...new Set(papers.flatMap(p=>p.topics))].sort();
const nav=[['/','Home'],['/research/','Research'],['/publications/','Publications'],['/team/','People'],['/resources/','Resources'],['/tractography/','Explore'],['/news/','News'],['/contact/','Contact']];
const routes=[];
fs.rmSync('dist',{recursive:true,force:true});fs.mkdirSync('dist');fs.cpSync('public','dist',{recursive:true});fs.writeFileSync('dist/.nojekyll','');
const org={'@context':'https://schema.org','@type':'ResearchOrganization',name:site.name,url:absolute('/'),logo:absolute('/assets/mac-logo.png'),parentOrganization:{'@type':'Organization',name:site.institution},sameAs:[site.github,site.scholar]};

function paperMetadata(p){
 const names=p.authorList?.length?p.authorList:[p.authors];
 const directPdf=p.pdf&&p.pdfAccess!=='needs-review'&&/\.pdf(?:[?#]|$)/i.test(p.pdf);
 const meta=[['citation_title',p.title],...names.map(n=>['citation_author',n]),['citation_publication_date',p.datePublished||String(p.year)],['citation_doi',(p.doi||'').replace('https://doi.org/','')],['citation_abstract_html_url',absolute(paperUrl(p))],[p.type==='Book chapter'?'citation_book_title':'citation_journal_title',p.journal],...(directPdf?[['citation_pdf_url',absolute(p.pdf)]]:[])].filter(([,v])=>v);
 const schema={'@context':'https://schema.org','@type':p.type==='Book chapter'?'Chapter':'ScholarlyArticle',headline:p.title,name:p.title,author:names.map(name=>({'@type':/consortium|study team|collaboration/i.test(name)?'Organization':'Person',name})),datePublished:p.datePublished||String(p.year),description:p.summary,abstract:p.description||p.summary,keywords:p.topics,genre:p.type,creativeWorkStatus:p.publicationStatus,url:absolute(paperUrl(p)),sameAs:[p.doi,p.publisher].filter(Boolean),isPartOf:{'@type':p.type==='Book chapter'?'Book':'Periodical',name:p.journal}};
 if(p.licenseUrl)schema.license=p.licenseUrl;if(p.openAccess===true)schema.isAccessibleForFree=true;
 if(directPdf)schema.encoding={'@type':'MediaObject',contentUrl:absolute(p.pdf),encodingFormat:'application/pdf'};
 return meta.map(([n,v])=>`<meta name="${n}" content="${e(v)}">`).join('')+`<script type="application/ld+json">${json(schema)}</script><link rel="alternate" type="text/markdown" href="${e(url(paperUrl(p)+'index.md'))}">`;
}
function layout(title,active,body,route,description,extra=''){
 let analytics='';
 if(site.analytics?.provider==='goatcounter'&&/^[a-z0-9][a-z0-9-]{1,60}$/.test(site.analytics.siteCode||''))analytics=`<script data-goatcounter="https://${e(site.analytics.siteCode)}.goatcounter.com/count" async src="https://gc.zgo.at/count.js"></script>`;
 else if(site.analytics?.provider==='plausible'&&/^https:\/\/plausible\.io\/js\/pa-[a-zA-Z0-9_-]+\.js$/.test(site.analytics.scriptUrl||''))analytics=`<script async src="${e(site.analytics.scriptUrl)}"></script><script>window.plausible=window.plausible||function(){(plausible.q=plausible.q||[]).push(arguments)};plausible.init=plausible.init||function(i){plausible.o=i||{}};plausible.init();</script>`;

 if(route.startsWith('/designs/'))analytics='';
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${e(title)} | Microstructure & Connectivity Lab</title><meta name="description" content="${e(description||'Diffusion MRI, tissue microstructure, and white matter connectivity research at Vanderbilt University Medical Center.')}"><meta name="robots" content="${route.startsWith('/designs/')?'noindex,nofollow':site.indexing?'index,follow,max-image-preview:large':'noindex,follow'}"><link rel="canonical" href="${e(absolute(route==='/home/'?'/':route))}"><link rel="icon" type="image/png" href="${e(url('/assets/mac-logo.png'))}"><link rel="stylesheet" href="${e(url('/style.css'))}"><script defer src="${e(url('/site.js'))}"></script><script type="application/ld+json">${json(org)}</script>${extra}${analytics}</head><body class="${active==='Home'?'home':'interior'}"><a class="skip" href="#main">Skip to content</a><header class="header"><div class="wrap header-inner">${link('/',image('/assets/mac-logo.png','M&C Lab logo','brand-logo',true)+'<span class="brand-title">Microstructure<br>& Connectivity Lab</span>','brand')}<button class="menu-toggle" aria-expanded="false" aria-controls="primary-nav">Menu</button><nav id="primary-nav" aria-label="Main navigation">${nav.map(([p,n])=>`<a href="${e(url(p))}" ${active===n?'aria-current="page"':''}>${n}</a>`).join('')}</nav></div></header><main id="main">${body}</main><footer><div class="wrap footer-main"><div class="footer-identity">${image('/assets/mac-logo.png','M&C Lab logo','footer-logo')}<p>Microstructure & Connectivity Lab<br>Vanderbilt University Medical Center</p></div><div><span class="eyebrow">Address</span><p>Vanderbilt University Institute of Imaging Science<br>${e(site.address)}</p></div><div><span class="eyebrow">Contact</span><p>${link('mailto:'+site.email,e(emailDisplay),'email-link')}<br>${link(site.github,'GitHub')} · ${link(site.scholar,'Google Scholar')}<br>${link('/publications.json','Publication metadata')} · ${link('/tractography/','Streamline viewer')}</p></div></div><div class="wrap footer-bottom"><span>Microstructure & Connectivity Lab</span><span>${site.reviewPreview?'Preview for lab feedback':'Vanderbilt University Medical Center'} · ${link('/privacy/','Privacy')}</span></div></footer></body></html>`;
}
function write(route,title,active,body,description,extra=''){
 const dest=path.join('dist',route,'index.html');fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,layout(title,active,body,route,description,extra));routes.push(route);
}
const intro=(eyebrow,title,description)=>`<section class="page-intro wrap"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1>${description?`<p class="lead">${description}</p>`:''}</section>`;
function actions(p){return `<div class="paper-actions">${p.pdf&&p.pdfAccess!=='needs-review'?link(p.pdf,'Read PDF ↗','text-link',`data-event="paper_download_click" data-paper-slug="${e(p.slug)}"`):''}${p.publisher||p.doi?link(p.publisher||p.doi,p.type==='Preprint'?'Read preprint ↗':p.type==='Book chapter'?'Book chapter ↗':'Published paper ↗','text-link'):''}${p.code?link(p.code,'Code ↗','text-link'):''}${p.dataset?link(p.dataset,'Data & models ↗','text-link'):''}${(p.links||[]).map(l=>link(l.url,e(l.label)+' ↗','text-link')).join('')}</div>`;}
const shortAuthors=p=>p.authorList?.length>8?p.authorList[0]+' et al. · Last author: '+p.authorList.at(-1):p.authors;
const fullAuthors=p=>p.authorList?.length>10?`<details class="long-authors"><summary>${e(shortAuthors(p))} · Show all ${p.authorList.length} authors</summary><p>${e(p.authors)}</p></details>`:`<p class="authors">${e(p.authors)}</p>`;
const typeLabel=p=>`${e(p.type)}${p.type==='Preprint'?' · not peer reviewed':''}`;
function card(p){return `<article class="paper-card" data-paper-slug="${e(p.slug)}">${p.image?link(paperUrl(p),image(p.image,p.imageAlt),'paper-picture'):''}<div class="paper-meta"><span>${e(p.journal)} · ${p.year}</span><span>${typeLabel(p)}</span></div><h3>${link(paperUrl(p),e(p.title))}</h3><p>${e(p.summary)}</p>${link(paperUrl(p),'Summary & resources →','text-link')}</article>`;}
const resourceType=r=>r.type==='Code'?'Software':r.type==='Dataset'?'Data & atlases':r.type==='Learning'?'Teaching':r.type;
function resourceCard(r){return `<article class="resource-card resource-${e(r.type?.toLowerCase())}" data-resource="${e(r.id||r.title)}"><span class="eyebrow">${e(resourceType(r))}${r.year?' · '+r.year:''}</span><h3>${link(r.id==='white-matter-brain-charts'?'/resources/#brain-charts':r.url,e(r.title))}</h3><p>${e(r.description)}</p><div class="resource-links">${link(r.id==='white-matter-brain-charts'?'/resources/#brain-charts':r.url,e(r.id==='white-matter-brain-charts'?'Software and data':r.linkLabel||'Open resource')+' ↗','text-link')}${r.paper?link(r.paper,'Related paper ↗','text-link'):''}${r.secondaryUrl?link(r.secondaryUrl,'DSI Studio guide ↗','text-link'):''}</div></article>`;}
const newsCard=n=>`<article class="news-card"><p class="news-date"><time datetime="${e(n.date)}">${e(new Date(n.date+'T12:00:00Z').toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'}))}</time> · ${e(n.publisher)}</p><h3>${link(n.url,e(n.title))}</h3><p>${e(n.summary)}</p><div class="paper-actions">${link(n.url,'Read story ↗','text-link')}${n.publicationSlug?link('/publications/'+n.publicationSlug+'/','Related research →','text-link'):''}</div></article>`;
function paperRows(list){return list.map(p=>`<article class="paper-row ${p.image?'':'no-figure'}" data-paper data-paper-slug="${e(p.slug)}" data-type="${e(p.type)}" data-year="${p.year}" data-topics="${e(json(p.topics))}" data-search="${e([p.title,p.authors,p.journal,p.year,...p.topics,p.summary].join(' ').toLowerCase())}"><div class="paper-year">${p.year}</div><div><div class="paper-meta"><span>${e(p.journal)}</span><span>${typeLabel(p)}</span></div><h2>${link(paperUrl(p),e(p.title))}</h2><p class="authors">${e(shortAuthors(p))}</p><p>${e(p.summary)}</p><div class="tag-row">${p.topics.map(t=>`<span class="tag">${e(t)}</span>`).join('')}</div><div class="paper-actions">${link(paperUrl(p),'Summary & resources →','text-link')}${p.pdf&&p.pdfAccess!=='needs-review'?link(p.pdf,'PDF ↗','text-link',`data-event="paper_download_click" data-paper-slug="${e(p.slug)}"`):''}${p.publisher||p.doi?link(p.publisher||p.doi,p.type==='Preprint'?'Read preprint ↗':p.type==='Book chapter'?'Read chapter ↗':'Read article ↗','text-link'):''}${p.fullText?link(p.fullText,'Open full text ↗','text-link'):''}</div></div>${p.image?link(paperUrl(p),image(p.image,p.imageAlt),'row-image'):''}</article>`).join('');}
const viewerPanel=(id,expanded=false)=>renderViewerPanel(id,expanded,{image,link,url});
const spotlight=nature?`<section class="nature-feature"><div class="wrap nature-grid"><div><p class="eyebrow">Nature · ${e(nature.datePublished||'2026')}</p><h2>${link(paperUrl(nature),e(nature.title))}</h2><p>${e(nature.summary)}</p>${link(paperUrl(nature),'Read the study and access the resources →','text-link')}${actions(nature)}</div>${nature.image?`<figure>${link(paperUrl(nature),image(nature.image,nature.imageAlt))}<figcaption>${e(nature.caption||'Kim et al., Nature, 2026.')}</figcaption></figure>`:''}</div></section>`:'';
const home=`<section class="hero"><div class="wrap hero-grid"><div class="hero-copy"><p class="eyebrow">Vanderbilt University Medical Center</p><h1>Microstructure<br>& Connectivity<br><em>Lab</em></h1><p>We develop and test MRI methods for measuring tissue organization and tracing white matter pathways in the brain and spinal cord.</p><div class="hero-actions">${link('/research/','Our research','button')}${link('/tractography/','Explore pathways ↗','button button-outline')}${link('/publications/','Publications','quiet-link')}</div></div>${viewerPanel('home')}</div></section>${spotlight}<section class="wrap section about-section"><div><p class="eyebrow">Research</p><h2>Measuring white matter.</h2><p class="section-copy">What can an MRI measurement tell us about tissue? Which pathways can tractography recover reliably? How does white matter change across the lifespan? These questions guide our work in acquisition, modeling, and validation.</p>${link('/research/','Research areas →','text-link')}</div><div class="research-list">${research.map(r=>link('/research/#'+r.id,`<span class="list-number">${r.number}</span><span>${e(r.short)}</span><span aria-hidden="true">↗</span>`,'research-link')).join('')}</div></section><section class="section publications-section"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">Publications</p><h2>Recent papers</h2></div>${link('/publications/','All publications →','text-link')}</div><div class="paper-grid">${published.filter(p=>p!==nature).slice(0,3).map(card).join('')}</div></div></section>${preprints.length?`<section class="wrap section"><div class="section-heading"><div><p class="eyebrow">Work in progress</p><h2>Preprints</h2></div>${link('/preprints/','All preprints →','text-link')}</div><div class="paper-grid">${preprints.slice(0,3).map(card).join('')}</div></section>`:''}<section class="wrap section"><div class="section-heading"><h2>Software and data</h2>${link('/resources/','All resources →','text-link')}</div><div class="resource-grid">${resources.filter(r=>['white-matter-brain-charts','synb0-disco','prequal'].includes(r.id)).map(resourceCard).join('')}</div></section><section class="wrap section home-news"><div class="section-heading"><h2>In the news</h2>${link('/news/','All news →','text-link')}</div><div class="news-grid">${news.slice(0,2).map(newsCard).join('')}</div></section><section class="viewer-banner"><div class="wrap"><div><p class="eyebrow">Tractography</p><h2>White matter, up close.</h2><p>Examine the arcuate, corticospinal, and callosal pathways. Compare their trajectories, isolate a bundle, or follow its central course.</p>${link('/tractography/','Open the streamline viewer →','button')}</div>${image('/assets/tractography-detail.webp','Arcuate, corticospinal, and callosal pathways rendered as illuminated tubes inside the matching brain')}</div></section>`;
const viewerScript=`<script defer src="${e(url('/viewer.js'))}"></script>`;
write('/','Home','Home',home,undefined,viewerScript);write('/home/','Home','Home',home,undefined,viewerScript);

write('/research/','Research','Research',intro('Research','Brain and spinal cord MRI','Acquisition, processing, biophysical modeling, and validation.')+`<div class="wrap research-areas">${research.map(r=>`<section class="research-area" id="${r.id}"><div><span class="eyebrow">${r.number} / ${e(r.short)}</span><h2>${e(r.title)}</h2><p>${e(r.description)}</p><div class="related-papers"><h3>Related publications</h3>${papers.filter(p=>p.topics.some(t=>r.topics.includes(t))).slice(0,3).map(p=>link(paperUrl(p),e(p.title)+' →')).join('')}</div></div>${r.image?`<figure>${link(r.image,image(r.image,r.alt))}<figcaption>${e(r.caption||'Select the figure to view it at full size.')}</figcaption></figure>`:`<div class="research-aside"><h3>${r.short==='Microstructure'?'MRI and histology':'Methods and reproducibility'}</h3><p>${r.short==='Microstructure'?'We test what diffusion measurements can resolve about tissue.':'Software, quality assurance, benchmark datasets, and practical recommendations.'}</p>${link(r.short==='Microstructure'?'/publications/?topic=Microstructure':'/resources/','Related work →','text-link')}</div>`}</section>`).join('')}</div>`);
function library(list,preprintOnly=false){return `<section class="wrap paper-library"><div class="publication-tabs">${link('/publications/','Published work',preprintOnly?'':'current')}${link('/preprints/','Preprints',preprintOnly?'current':'')}${link('/publications/publications-list/','By year')}</div><div class="library-controls"><label for="paper-search">Search publications<input type="search" id="paper-search" placeholder="Title, author, topic, or finding"></label><div class="library-selects"><label>Type<select id="paper-type"><option value="All">All types</option>${[...new Set(list.map(p=>p.type))].sort().map(t=>`<option>${e(t)}</option>`).join('')}</select></label><label>Year<select id="paper-year"><option value="All">All years</option>${[...new Set(list.map(p=>p.year))].sort((a,b)=>b-a).map(y=>`<option>${y}</option>`).join('')}</select></label></div><div class="filters" role="group" aria-label="Filter by research topic">${['All',...topics].map(t=>`<button data-filter="${e(t)}" aria-pressed="${t==='All'}">${e(t)}</button>`).join('')}</div></div><p class="selection-note">${preprintOnly?'Preprints have not completed peer review.':''} ${link(site.scholar,'Google Scholar ↗')}</p><p id="result-count" class="result-count" role="status" aria-live="polite">${list.length} publications</p>${paperRows(list)}<p id="empty-results" hidden>No publications match these filters.</p></section>`;}
write('/publications/','Publications','Publications',intro('Publications','Papers, reviews, and chapters','Research findings, methodological studies, and practical guidance.')+library(published));
write('/preprints/','Preprints','Publications',intro('Preprints','Current preprints','Early versions of ongoing work. Findings may change through peer review.')+library(preprints,true));

for(const p of papers){
 const route=paperUrl(p),notes=p.findings?.length?`<section><h2>${p.type==='Review'||p.type==='Book chapter'?'Topics covered':'Main findings'}</h2><ul class="findings">${p.findings.map(f=>`<li>${e(f)}</li>`).join('')}</ul></section>`:'';
 const body=`<article class="wrap paper-detail" data-paper-slug="${e(p.slug)}">${link(p.type==='Preprint'?'/preprints/':'/publications/','← '+(p.type==='Preprint'?'All preprints':'All publications'),'back-link')}<p class="eyebrow">${p.year} / ${e(p.journal)} / ${typeLabel(p)}</p><h1>${e(p.title)}</h1>${fullAuthors(p)}${p.type==='Preprint'?'<p class="preprint-note">Preprint · This work has not completed peer review.</p>':''}${actions(p)}<div class="tag-row">${p.topics.map(t=>link('/publications/?topic='+encodeURIComponent(t),e(t),'tag')).join('')}</div><div class="paper-body ${p.image?'':'no-figure'}"><div><section><h2>Summary</h2><p class="paper-summary">${e(p.summary)}</p></section><section><h2>${p.type==='Review'||p.type==='Book chapter'?'Scope':'Study overview'}</h2><p>${e(p.description||p.summary)}</p></section>${notes}${p.limitations?`<section><h2>Interpretation</h2><p>${e(p.limitations)}</p></section>`:''}</div>${p.image?`<figure>${link(p.image,image(p.image,p.imageAlt))}<figcaption>${e(p.caption||'Figure from this work.')} ${p.figureSource?link(p.figureSource,'Source')+' · ':''}${p.figureLicense?link(p.figureLicense,'License')+' · ':''}Select the figure to view at full size.</figcaption></figure>`:''}</div>${p.resources?.length?`<section class="paper-resources"><h2>Data, models, and software</h2><div class="resource-grid">${p.resources.map(r=>resourceCard({...r,title:r.label})).join('')}</div></section>`:''}${p.correction?`<p class="small-note">${link(p.correction,e(p.correctionNote||'Publisher correction'))}</p>`:''}<section class="citation-section"><h2>Cite this work</h2><p>${e(shortAuthors(p))} (${p.year}). ${e(p.title)}. <em>${e(p.journal)}</em>. ${p.doi?link(p.doi,e(p.doi)):''}</p><div class="paper-actions">${link(route+'citation.bib','BibTeX','text-link')}${link(route+'index.md','Plain-text summary','text-link')}</div><p class="small-note">This page summarizes the work; consult the original article for the complete methods, results, and qualifications.</p></section><section class="related-papers"><h2>Related publications</h2>${papers.filter(q=>q!==p&&q.topics.some(t=>p.topics.includes(t))).slice(0,3).map(q=>link(paperUrl(q),e(q.title)+' →')).join('')}</section></article>`;
 write(route,p.title,'Publications',body,p.summary,paperMetadata(p));
 const bibSafe=s=>String(s||'').replace(/[{}]/g,'').replace(/&/g,'\\&');
 const entryType=p.type==='Book chapter'?'incollection':p.type==='Preprint'?'misc':'article';
 const bib=`@${entryType}{${p.slug}-${p.year},\n  title = {${bibSafe(p.title)}},\n  author = {${bibSafe((p.authorList||[p.authors]).join(' and '))}},\n  year = {${p.year}},\n  ${p.type==='Book chapter'?'booktitle':'journal'} = {${bibSafe(p.journal)}},\n  doi = {${bibSafe((p.doi||'').replace('https://doi.org/',''))}},\n  url = {${p.doi||absolute(route)}}\n}\n`;
 fs.writeFileSync(path.join('dist',route,'citation.bib'),bib);
 const md=`# ${p.title}\n\n${p.authors}\n\n${p.journal} · ${p.year} · ${p.type}${p.type==='Preprint'?' (not peer reviewed)':''}\n\n${p.doi||''}\n\n## Summary\n\n${p.summary}\n\n## Study overview\n\n${p.description||p.summary}\n\n## Findings / topics\n\n${(p.findings||[]).map(f=>'- '+f).join('\n')}\n\n## Resources\n\n${[[p.publisher||p.doi,'Original work'],[p.pdfAccess!=='needs-review'?p.pdf:null,'PDF'],[p.code,'Code'],[p.dataset,'Data and models'],...(p.links||[]).map(l=>[l.url,l.label])].filter(([u])=>u).map(([u,l])=>`- [${l}](${absolute(u)})`).join('\n')}\n\n${p.limitations?'## Interpretation\n\n'+p.limitations+'\n\n':''}Lab page: ${absolute(route)}\n\nThis is a research summary, not the full article.\n`;
 fs.writeFileSync(path.join('dist',route,'index.md'),md);
}
const legacyTopics={'notable-publications':null,'tractography':'Tractography','spinal-cord':'Spinal Cord','image-processing':'Image Processing','microstructure':'Microstructure','functional-connectivity':'Functional Connectivity','reviews-commentary-consensus':'Reviews & Consensus'};
for(const [slug,topic] of Object.entries(legacyTopics)){
 const list=topic?published.filter(p=>p.topics.includes(topic)):published.filter(p=>p.featured);
 write('/publications/'+slug+'/',topic||'Notable publications','Publications',intro('Publication collection',e(topic||'Notable publications'),'')+`<section class="wrap paper-library">${link('/publications/','← All publications','back-link')}${paperRows(list)}</section>`);
}
write('/publications/publications-list/','Publications by year','Publications',intro('Archive','Publications by year','Published work and preprints, with publication type shown for each entry.')+`<section class="wrap paper-library">${link('/publications/','Search and filter →','text-link')}${paperRows(papers)}</section>`);
const person=p=>`<article class="person">${p.image?image(p.image,p.name):`<div class="person-initials" aria-hidden="true">${p.name.split(' ').slice(0,2).map(v=>e(v[0])).join('')}</div>`}<div><h3>${e(p.name)}</h3><p class="person-role">${e(p.role)}</p><p>${e(p.interests)}</p>${p.profile?link(p.profile,'Full profile →','text-link'):''}</div></article>`;
write('/team/','People','People',intro('People','Lab members and collaborators','Researchers at Vanderbilt University Medical Center and Vanderbilt University.')+`<section class="wrap team-section"><h2>Lab members</h2><div class="people-grid">${team.filter(p=>p.group==='Lab').map(person).join('')}</div><h2>Collaborators</h2><p>We work closely with the ${link('https://my.vanderbilt.edu/masi/','MASI Lab')} (Bennett Landman) and ${link('https://lab.vanderbilt.edu/nob/','NOB Lab')} (Seth Smith).</p><div class="people-grid">${team.filter(p=>p.group==='Collaborators').map(person).join('')}</div></section>`);
write('/team/kurt-schilling/','Kurt G. Schilling','People',intro('Principal investigator','Kurt G. Schilling, PhD','Assistant Professor, Vanderbilt University Medical Center')+`<section class="wrap profile-page">${image('/assets/kurt.png','Kurt Schilling')}<div><p>Kurt Schilling is an Assistant Professor in Radiology and Radiological Sciences at Vanderbilt University Medical Center and in Electrical and Computer Engineering at Vanderbilt University.</p><p>His research focuses on measuring tissue microstructure and structural connectivity with MRI. His group develops and evaluates diffusion MRI methods for the brain and spinal cord, using histology and anatomical reference data to test what these measurements can resolve. Current work includes tractography validation, white matter variation across the lifespan, superficial white matter, and spinal cord imaging.</p><p>He earned his PhD in Biomedical Engineering at Vanderbilt University, completed postdoctoral training at the Vanderbilt University Institute of Imaging Science, and joined the faculty as a Research Assistant Professor in 2020.</p><div class="paper-actions">${link(site.scholar,'Google Scholar ↗','text-link')}${link(site.github,'GitHub ↗','text-link')}${link('/contact/','Contact','text-link')}</div>${link('/publications/','Publications →','text-link')}</div></section>`);
const chartResources=resources.find(r=>r.id==='white-matter-brain-charts');
const resourcesPage=intro('Resources','Software, data & teaching','Tools to process diffusion MRI, data to test methods, and material for learning tractography.')+`<div class="wrap resources-page"><nav class="resource-nav" aria-label="Resource sections">${[['software','Software'],['datasets','Data & atlases'],['teaching','Lectures & practicals']].map(([id,label])=>link('#'+id,label)).join('')}${link('/tractography/','Pathway explorer ↗')}</nav><section id="software"><div class="section-heading"><div><p class="eyebrow">01 / Software</p><h2>Processing and analysis</h2></div></div><article class="brain-chart-project" id="brain-charts" data-resource="white-matter-brain-charts"><div><p class="eyebrow">White Matter Brain Charts · Nature 2026</p><h3>Lifespan models, software, and data</h3><p>${e(chartResources.description)}</p>${link('/publications/white-matter-lifespan-brain-charts/','Read the study →','text-link')}</div><div class="chart-project-links">${chartResources.links.map((r,i)=>link(r.url,`<span class="project-link-number">0${i+1}</span><span><strong>${e(r.label)}</strong><small>${['Fit and apply lifespan reference models','Extract and prepare pathway measurements','Run the processing environment','Permitted derived features and centile scores'][i]}</small></span><span aria-hidden="true">↗</span>`)).join('')}</div></article><div class="resource-grid">${resources.filter(r=>r.type==='Code'&&r.id!=='white-matter-brain-charts').map(resourceCard).join('')}</div></section><section id="datasets"><div class="section-heading"><div><p class="eyebrow">02 / Data</p><h2>Datasets and atlases</h2></div></div><div class="resource-grid">${resources.filter(r=>r.type==='Dataset').map(resourceCard).join('')}</div></section><section id="teaching"><div class="section-heading"><div><p class="eyebrow">03 / Teaching</p><h2>Lectures and practicals</h2></div></div><div class="resource-grid">${resources.filter(r=>r.type==='Learning').map(resourceCard).join('')}</div></section><aside class="resource-explore"><div><p class="eyebrow">Interactive anatomy</p><h2>Explore white matter pathways</h2><p>Rotate reconstructed bundles, compare their central trajectories, and save a view.</p>${link('/tractography/','Open the pathway explorer →','button')}</div>${image('/assets/tractography-detail.webp','Reconstructed white matter pathways')}</aside></div>`;
write('/resources/','Software, data & teaching','Resources',resourcesPage);
designPreviews({layout,write,resourcesPage,link,url,fs,path,routes});
write('/news/','News','News',intro('News','Research in the news','Stories and interviews about the lab’s work.')+`<section class="wrap news-page">${news.map(newsCard).join('')}</section>`);
write('/contact/','Contact','Contact',intro('Contact','Contact the lab','For research questions and collaboration, contact Kurt Schilling.')+`<section class="wrap contact-grid"><div><p class="eyebrow">Email</p><h2>${link('mailto:'+site.email,e(emailDisplay),'email-link')}</h2><p class="eyebrow">Opportunities</p><p>There are no open positions at the moment.</p><p class="eyebrow">Address</p><p>Vanderbilt University Institute of Imaging Science<br>Vanderbilt University Medical Center<br>${e(site.address)}</p></div><aside><h2>Research and resources</h2>${nav.filter(([p])=>['/research/','/team/','/resources/'].includes(p)).map(([p,n])=>link(p,n+' →','contact-link')).join('')}</aside></section>`);
write('/tractography/','Pathway explorer','Explore',`<section class="wrap explorer-intro"><div><p class="eyebrow">Tractography</p><h1>Pathway explorer</h1></div><p>Drag to rotate. Scroll to zoom.<br>Choose pathways, colors, and anatomy below.</p></section><section class="wrap viewer-section">${viewerPanel('full',true)}<details class="viewer-methods"><summary>About these reconstructions</summary><div class="viewer-notes"><p>The viewer preserves every streamline and original point in the left and right arcuate, left and right corticospinal, and CC_4 callosal reconstructions. These are tractography trajectories, not individual axons.</p><p>Centroids describe the mean trajectory within each reconstruction after aligning streamline direction and sampling along its length. They summarize bundle shape; they are not additional measured fibers. In combined mode, centroids are overlaid in a contrasting color to keep their paths visible. The transparent surface is the matching diffusion-space brain mask, smoothed for display.</p><p>Pathway colors are adjustable. Local orientation coloring uses red for left–right, green for anterior–posterior, and blue for superior–inferior. Colors do not measure tissue properties.</p></div></details></section>`,'Explore reconstructed white matter pathways with tract centroids, adjustable colors, and a transparent brain.',viewerScript);
write('/privacy/','Privacy','',intro('Privacy','Site privacy','')+`<section class="wrap prose-page"><p>${site.analytics?'This site uses '+(site.analytics.provider==='goatcounter'?'GoatCounter':'Plausible Analytics')+' to count visits and interactions, including clicks on paper links.':'This preview does not include analytics or download tracking.'} There is no account registration or contact form.</p><p>Links to publishers, GitHub, Google Scholar, Google Drive, and Zenodo take you to services with their own privacy practices. The hosting provider may process request information to serve this website.</p><p>PDF-link clicks provide a measure of interest in a paper. It will not establish that a file finished downloading or was read. Downloads made directly from a publisher or repository will not appear in the lab website’s click counts.</p><p>Contact: ${link('mailto:'+site.email,e(emailDisplay),'email-link')}.</p></section>`);
fs.writeFileSync('dist/404.html',layout('Page not found','',intro('404','This page could not be found.',`Return to ${link('/','the homepage')} or browse ${link('/publications/','publications')}.`),'/404.html'));
fs.writeFileSync('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.filter(r=>r!=='/home/'&&!r.startsWith('/designs/')).map(r=>`<url><loc>${e(absolute(r))}</loc></url>`).join('')}</urlset>`);
fs.writeFileSync('dist/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${absolute('/sitemap.xml')}\n`);
const publicPapers=papers.map(p=>{const {localSourceFile,pdfAccess,...record}=p;if(pdfAccess==='needs-review')delete record.pdf;return {...record,url:absolute(paperUrl(p))};});
fs.writeFileSync('dist/publications.json',JSON.stringify(publicPapers,null,2));
fs.writeFileSync('dist/llms.txt',`# Microstructure & Connectivity Lab\n\nDiffusion MRI, tissue microstructure, and white matter connectivity research at Vanderbilt University Medical Center.\n\n## Research and publications\n\n- [Research](${absolute('/research/')})\n- [Publications](${absolute('/publications/')})\n- [Preprints: not peer reviewed](${absolute('/preprints/')})\n- [Publication metadata](${absolute('/publications.json')})\n- [Software and data](${absolute('/resources/')})\n- [News](${absolute('/news/')})\n\n## Paper summaries\n\n${papers.map(p=>`- [${p.title}](${absolute(paperUrl(p)+'index.md')}): ${p.type}, ${p.year}.`).join('\n')}\n\nPaper pages summarize published findings; the original works remain the authoritative source.\n`);
fs.writeFileSync('dist/build-info.json',JSON.stringify({base,routes,papers:papers.length,preprints:preprints.length},null,2));
console.log(`Built ${routes.length} pages from ${papers.length} publication records (${preprints.length} preprints). Base path: ${base||'/'}`);
